spring:
  application:
    name: order-api


  cloud:
    openfeign:
      okhttp:
        enabled: true
  datasource:
    url: jdbc:h2:file:/Users/hidongmin37/mem-data.mv.db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


server:
  port: 8083

mailgun:
  key: test-mailgun-key