spring:
  application:
    name: order-api

  cloud:
    openfeign:
      okhttp:
        enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS commerce\;SET SCHEMA commerce

    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_schema: commerce
        org.hibernate.envers.audit_table_suffix: _AUD
        org.hibernate.envers.revision_field_name: REV
        org.hibernate.envers.revision_type_field_name: REVTYPE

server:
  port: 8083

mailgun:
  key: test-mailgun-key